CREATE TABLE IF NOT EXISTS employees
(
    emp_ID INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(50) NOT NULL,
    email VARCHAR(250) NOT NULL UNIQUE,
    phone CHAR(10) NOT NULL,
    age TINYINT NOT NULL,
    national_ID CHAR(14) NOT NULL UNIQUE,
    role_ID INT NOT NULL,
    FOREIGN KEY (role_ID) REFERENCES roles(roles_ID)
);
